### ISSUE TITLE
Use animated cameras in evalQuality for tracking

### ISSUE THREAD

**Issue by caymard** [poparteu/openMVG#160]
To evaluate tracking use animated cameras:
* [x] evalQuality should be able to compare two animated abc (no UID)
* [x] convert the .camera of the levallois dataset into a animated abc
* [x] PR the changes on the dataset levallois

**Comment by simogasp** [comment]
@caymard so let's go with animated cameras for comparing tracking results

**Comment by fabiencastan** [comment]
@caymard status?

**Comment by simogasp** [comment]
@fabiencastan when we compare 2 animated cameras, if the ground truth one is built with UID it will mess the order of the frames (we are not using UID in `cameraLocalization` and if we do we won't be able to see the tracking as a smooth trajectory but it will jump from one frame to another in Maya). So for the GT of tracking sequences we can just use incremental IDs for frames as we do in cameraLocalization.

**Comment by fabiencastan** [comment]
I don't understand the discussion.

The cameraLocalization doesn't generate an openMVG sfm_data but directly an animated camera in alembic. So there is no notion of ID at all.

So to compare with the ground truth we have in maya, we just need to export the animated camera from maya in abc. The 2 animated cameras will be loaded in the same way in openMVG and we will be able to compare them.

**Comment by simogasp** [comment]
@fabiencastan @caymard  because there some missing steps
The facts:

1. there is a maya script to export the camera movement as an animated abc (cf slack)
2. the generated file for some reason it's not working: it seems there is a regularly missing frame (one every 24 frames) and its GT trajectory does not align with the one generated by cameraLocalization (like there is not a correct correspondence among the frames)
3. we tried to generate the animated GT from the .camera, as debugging and as possible useful new binary to have
4. here was the above problem with UID, so for animated GT the UID must not be used (if we ever decide to keep that new binary). With such animated GT everything works fine
5. we compared the GT generated by the maya script and the GT generated from the .camera files, and the problem persists.
6. the problem may be in the maya abc exporter

**Comment by fabiencastan** [comment]
So the problem is the usage of [ISampleSelector](https://github.com/poparteu/openMVG/blob/popart_develop/src/openMVG/sfm/AlembicImporter.cpp#L330) using time instead of indexes in AlembicImporter, which makes the importer valid only for 24fps scenes when using animated cameras.

**Comment by caymard** [comment]
PR #188
